name: Auto Update Website Data
on:
  schedule:
    # 每天 UTC 时间 8:00 运行（北京时间 16:00）
    - cron: '0 8 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # 3. 安装依赖
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pytz
        
      # 4. 执行数据更新脚本
      - name: Run data update script
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}  # 安全存储的密钥
        run: python .github/scripts/update_data.py
        
      # 5. 提交更改
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Update data"
          git push